AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deployment for serverless API

Globals:
    Api:
        BinaryMediaTypes:
            - "*~1*"

Resources:
  GenOTP:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      CodeUri: gen-otp/
      Events:
        GetApi:
          Type: Api
          Properties:
            # nric will be passed through query params
            Path: /user/otp
            Method: get

  ChatHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      CodeUri: chat-hook/
      Events:
        MessengerHook:
          Type: Api
          Properties:
            Path: /messenger/hook
            Method: post
        TelegramHook:
            Type: Api
            Properties:
              Path: /telegram/hook
              Method: post

  WriteMessageToDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      CodeUri: write-message-to-db/
      Timeout: 30
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /message
            Method: post

  SendMessageToUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-message/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Policies: AWSLambdaDynamoDBExecutionRole
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
