AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deployment for serverless API

Globals:
    Api:
        BinaryMediaTypes:
            - "*~1*"

Resources:
  GenOTP:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      CodeUri: gen-otp/
      Timeout: 30
      Policies: arn:aws:iam::247544061391:policy/WogiDynamoDBFullAccess
      Events:
        GetApi:
          Type: Api
          Properties:
            # nric will be passed through query params
            Path: /user/otp
            Method: get

  ChatHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      CodeUri: chat-hook/
      Timeout: 30
      Policies: arn:aws:iam::247544061391:policy/WogiDynamoDBFullAccess
      Events:
        MessengerHook:
          Type: Api
          Properties:
            Path: /messenger/hook
            Method: post
        TelegramHook:
            Type: Api
            Properties:
              Path: /telegram/hook
              Method: post
        NewMessageDeliveriesStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MessageDeliveriesTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  WriteMessageToDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      CodeUri: write-message-to-db/
      Timeout: 30
      Policies: arn:aws:iam::247544061391:policy/WogiDynamoDBFullAccess
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /message
            Method: post

  CreateMessageDeliveries:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-message-deliveries/
      Timeout: 30
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Policies: arn:aws:iam::247544061391:policy/WogiDynamoDBFullAccess
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MessagesTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  SendMessage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-message/
      Timeout: 30
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Policies: arn:aws:iam::247544061391:policy/WogiDynamoDBFullAccess
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MessageDeliveriesTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wogi-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wogi-messages
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  MessageDeliveriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wogi-message-deliveries
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wogi-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE